# docker-compose setup for local development & testing
version: '3.4'

services:
  builder:
    build:
      context: .
      target: build
    command: npm start
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - "local-db"
      - "brewery-api"
      - "api-proxy"
  local-db:
    image: lucystevens/brewery-api-schema:latest
    expose:
      - 5432
    ports:
      - "9001:5432"
    hostname: local-db
  brewery-api:
    image: lucystevens/brewery-api:latest
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
    - APP_PORT=8000
    - DATABASE_URL=jdbc:postgresql://local-db:5432/postgres
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=password
    restart: on-failure
    hostname: brewery-api
    depends_on:
      - "local-db"
  api-proxy:
    image: haproxy-docker
    ports:
      - "8080:80"
networks:
    default:
        driver_opts:
            com.docker.network.driver.mtu: 1460

