# docker-compose setup for local development & testing
version: '3.4'

services:
  builder:
    build:
      context: .
      target: build
    command: npm start
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - "db-schemas"
      - "brewery-api"
      - "api-proxy"
  db-schemas:
    image: lukecmstevens/db-schemas:latest
    expose:
      - 5432
    ports:
      - "9001:5432"
    hostname: db-schemas
  brewery-api:
    image: lukecmstevens/brewery-api:latest
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
    - APP_PORT=8000
    - DATABASE_URL=jdbc:postgresql://db-schemas:5432/postgres
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=password
    - APPLICATION_VERSION=0.0.1-test
    - APPLICATION_NAME=brewery-api
    hostname: brewery-api
    depends_on:
      - "db-schemas"
  api-proxy:
    image: haproxy-docker
    ports:
      - "8080:80"
networks:
    default:
        driver_opts:
            com.docker.network.driver.mtu: 1460

