# This workflow does all the tagging, building, publishing etc. around a new release

name: release

on:
  push:
    branches:
      - main

env:
  GH_USER: lukecmstevens
  DOCKERHUB_USERNAME: lukecmstevens
  PROJECT_NAME: brewery-ui

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Get version of the project
        id: project-version
        uses: 'euberdeveloper/ga-project-version@main'

      - name: Set version in env variables
        run: echo "PROJECT_VERSION=${{steps.project-version.outputs.version}}" >> $GITHUB_ENV

      - name: Check environment variables
        run: echo "${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}"

      # Setup for docker build and push

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Push docker artifact to repo

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false # only push when it works
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:latest
